//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionBoard
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOrder
    {
        public int Id { get; set; }
        public string Material { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> UnitofMeasurement { get; set; }
        public Nullable<int> Project { get; set; }
    
        public virtual TblProject TblProject { get; set; }
        public virtual TblUOM TblUOM { get; set; }
    }
}
