//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionBoard
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblprojectImg
    {
        public int Id { get; set; }
        public string Img1 { get; set; }
        public string Img2 { get; set; }
        public string img3 { get; set; }
        public string img4 { get; set; }
        public string img5 { get; set; }
        [Display(Name ="Project Name")]
        public Nullable<int> ProjectId { get; set; }
    
        public virtual TblProject TblProject { get; set; }
    }
}
